import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Snow from "../service/snowfall";
import "./globals.css";
import Head from "./head";
const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <Head />
         <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen h-screen overflow-x-hidden overflow-y-hidden`}
         >
            <Snow /> 
            <div
               className="w-full h-full bg-cover bg-center bg-no-repeat"
               style={{
                  backgroundImage: `url(../../background.jpg)`,
               }}
            >
               {children}
            </div>
            <audio loop className="invisible w-0 h-0 background-music" src={"../../sounds/background-music.mp3"}></audio>
         </body>
      </html>
   );
}
